name: Internal Contributor of the Month

on:
  push:
    branches:
      - 'contributor-workflow'

jobs:
  determine-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine contributor
        id: determine
        run: |
          # Determine the start and end dates of the previous month
          START_DATE=$(date -d "last month" +%Y-%m-01)
          END_DATE=$(date -d "last month +1 month -1 day" +%Y-%m-%d)
          MONTH_NAME=$(date -d "last month" +%B)

          # Exclude certain users
          EXCLUDED_USERS=("VadymSachenko" "lenadoc" "andriitserkovnyi" "AlexSlawinski")  # Add the usernames to be excluded here

          # Count PRs for each user
          declare -A PR_COUNTS=()
          declare -A USER_INFO=()

          PAGE=1
          TOTAL_PR=0
          while : ; do
            # Fetch merged pull requests within the previous month
            PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github.v3+json" \
                   "https://api.github.com/repos/spryker/spryker-docs/pulls?state=closed&base=master&sort=created&direction=desc&merge_state=merged&page=$PAGE&per_page=100" \
                   | jq -r --arg START "$START_DATE" --arg END "$END_DATE" 'map(select(.merged_at >= $START and .merged_at <= $END)) | .[].user')

            if [ -z "$PRS" ]; then
              break
            fi

            for PR in $PRS; do
              USER=$(echo $PR | jq -r '.login')
              if [[ ! " ${EXCLUDED_USERS[@]} " =~ " ${USER} " ]]; then
                PR_COUNTS[$USER]=$((PR_COUNTS[$USER]+1))
                TOTAL_PR=$((TOTAL_PR+1))

                if [[ -z ${USER_INFO[$USER]} ]]; then
                  INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/users/$USER")
                  REAL_NAME=$(echo $INFO | jq -r '.name // ""')
                  EMAIL=$(echo $INFO | jq -r '.email // ""')
                  USER_INFO[$USER]="$REAL_NAME,$EMAIL"
                fi
              fi
            done

            ((PAGE++))
          done

          # Prepare contributors list
          CONTRIBUTORS=""
          for USER in "${!PR_COUNTS[@]}"; do
            COUNT="${PR_COUNTS[$USER]}"
            INFO="${USER_INFO[$USER]}"
            CONTRIBUTORS+="$USER, $INFO (PRs: $COUNT)\n"
          done

          # Sort contributors by PR count
          CONTRIBUTORS=$(echo -e "$CONTRIBUTORS" | sort -t '(' -k2 -n -r)

          TOTAL_CONTRIBUTORS=${#PR_COUNTS[@]}
          TOP_CONTRIBUTOR=$(echo -e "$CONTRIBUTORS" |I apologize for the abrupt cut-off in the previous message. Here is the completion of that code block:

```yaml
          head -n 1)
          TOP_CONTRIBUTOR_COUNT=$(echo $TOP_CONTRIBUTOR | awk -F'[()]' '{print $2}' | tr -dc '0-9')

          echo "CONTRIBUTORS=${CONTRIBUTORS}" >> $GITHUB_ENV
          echo "MONTH_NAME=${MONTH_NAME}" >> $GITHUB_ENV
          echo "TOTAL_CONTRIBUTORS=${TOTAL_CONTRIBUTORS}" >> $GITHUB_ENV
          echo "TOTAL_PR=${TOTAL_PR}" >> $GITHUB_ENV
          echo "TOP_CONTRIBUTOR=${TOP_CONTRIBUTOR}" >> $GITHUB_ENV
          echo "TOP_CONTRIBUTOR_COUNT=${TOP_CONTRIBUTOR_COUNT}" >> $GITHUB_ENV

      - name: Log contributors
        run: |
          CONTRIBUTORS="${{ env.CONTRIBUTORS }}"
          MONTH_NAME="${{ env.MONTH_NAME }}"
          TOTAL_CONTRIBUTORS="${{ env.TOTAL_CONTRIBUTORS }}"
          TOTAL_PR="${{ env.TOTAL_PR }}"
          TOP_CONTRIBUTOR="${{ env.TOP_CONTRIBUTOR }}"
          TOP_CONTRIBUTOR_COUNT="${{ env.TOP_CONTRIBUTOR_COUNT }}"

          # Print all contributors of the month and the number of PRs they created
          echo -e "In $MONTH_NAME, we had $TOTAL_CONTRIBUTORS contributors, with a total number of $TOTAL_PR PRs. Thank you, guys, for your great job. Keep up the awesome work."
          echo "Here are the detailed results:"
          echo -e "$CONTRIBUTORS"
          echo -e "Our top contributor of the month is $TOP_CONTRIBUTOR — $TOP_CONTRIBUTOR_COUNT PRs in total."
