name: Internal Contributor of the Month

on:
  push:
    branches:
      - 'contributor-workflow'

jobs:
  determine-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine contributors
        id: determine
        run: |
          # Fetch merged pull requests
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/spryker/spryker-docs/pulls?state=merged&base=master" \
                 | jq -r '.[].user.login')

          # Exclude certain users
          EXCLUDED_USERS=("VadymSachenko" "lenadoc" "andriitserkovnyi" "AlexSlawinski")  # Add the usernames to be excluded here

          # Filter out excluded users
          PRS_FILTERED=$(echo "$PRS" | grep -vF "${EXCLUDED_USERS[@]}")

          # Determine the top 3 contributors and the number of PRs they created
          CONTRIBUTORS=$(echo "$PRS_FILTERED" | sort | uniq -c | sort -nr | head -n3 | awk '{print $2, $1}')

          echo "CONTRIBUTORS=${CONTRIBUTORS}" >> $GITHUB_ENV

      - name: Log contributors
        run: |
          CONTRIBUTORS="${{ env.CONTRIBUTORS }}"

          # Print the top 3 contributors of the month and the number of PRs they created
          echo "Top Contributors of the Month:"
          echo "$CONTRIBUTORS" | while read -r contributor prs; do echo "- $contributor: $prs PRs"; done
