name: Internal Contributor of the Month

on:
  push:
    branches:
      - 'contributor-workflow'

jobs:
  determine-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine contributors
        id: determine
        run: |
          # Fetch merged pull requests
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/spryker/spryker-docs/pulls?state=merged&base=master" \
                 | jq -r '.[].user.login')

          # Exclude certain users
          EXCLUDED_USERS=("VadymSachenko" "lenadoc" "andriitserkovnyi" "AlexSlawinski")  # Add the usernames to be excluded here

          # Determine the top 3 contributors and the number of PRs they created
          CONTRIBUTORS=()
          for user in $PRS; do
            excluded=false
            for excludedUser in "${EXCLUDED_USERS[@]}"; do
              if [[ $user == $excludedUser ]]; then
                excluded=true
                break
              fi
            done
            if [[ $excluded == false ]]; then
              CONTRIBUTORS+=("$user")
            fi
          done

          # Get the count of PRs for each contributor
          CONTRIBUTORS_COUNT=()
          for contributor in "${CONTRIBUTORS[@]}"; do
            count=$(grep -cF "$contributor" <<< "$PRS")
            CONTRIBUTORS_COUNT+=("$contributor $count")
          done

          # Sort contributors by PR count in descending order
          SORTED_CONTRIBUTORS=($(echo "${CONTRIBUTORS_COUNT[@]}" | tr ' ' '\n' | sort -k2nr -k1 | tr '\n' ' '))

          # Take the top 3 contributors
          TOP_3_CONTRIBUTORS=("${SORTED_CONTRIBUTORS[@]:0:3}")

          echo "CONTRIBUTORS=${TOP_3_CONTRIBUTORS[*]}" >> $GITHUB_ENV

      - name: Log contributors
        run: |
          CONTRIBUTORS=(${{ env.CONTRIBUTORS }})

          # Print the top 3 contributors of the month and the number of PRs they created
          echo "Top Contributors of the Month:"
          for contributor in "${CONTRIBUTORS[@]}"; do
            echo "- $contributor"
          done
