name: Internal Contributor of the Month

on:
  push:
    branches:
      - '*'

jobs:
  determine-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine contributor
        id: determine
        run: |
          # Fetch merged pull requests
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/spryker/spryker-docs/pulls?state=closed&base=master" \
                 | jq -r '.[].user.login')

          # Determine the contributor with the most merged PRs
          CONTRIBUTOR=$(echo "$PRS" | sort | uniq -c | sort -nr | awk '{print $2}' | head -n1)

          echo "CONTRIBUTOR=${CONTRIBUTOR}" >> $GITHUB_ENV

      - name: Log contributor
        run: |
          CONTRIBUTOR="${{ env.CONTRIBUTOR }}"

          # Print the contributor of the month
          echo "Internal Contributor of the Month: $CONTRIBUTOR"
