name: Internal Contributor of the Month

on:
  push:
    branches:
      - 'contributor-workflow'

jobs:
  determine-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine contributor
        id: determine
        run: |
          # Determine the start and end dates of the previous month
          START_DATE=$(date -d "last month" +%Y-%m-01)
          END_DATE=$(date -d "last month +1 month -1 day" +%Y-%m-%d)
          MONTH_NAME=$(date -d "last month" +%B)

          # Fetch merged pull requests within the previous month
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/spryker/spryker-docs/pulls?state=closed&base=master&sort=created&direction=desc" \
                 | jq -r --arg START "$START_DATE" --arg END "$END_DATE" 'map(select(.merged_at >= $START and .merged_at <= $END)) | .[].user.login')

          # Exclude certain users
          EXCLUDED_USERS=("VadymSachenko" "lenadoc" "andriitserkovnyi" "AlexSlawinski")  # Add the usernames to be excluded here

          # Filter out excluded users
          PRS_FILTERED=""
          for USER in $PRS; do
            if [[ ! " ${EXCLUDED_USERS[@]} " =~ " ${USER} " ]]; then
              PRS_FILTERED+=" $USER"
            fi
          done

          # Determine the top 3 contributors and the number of PRs they created
          CONTRIBUTORS=$(echo "$PRS_FILTERED" | sort | uniq -c | sort -nr | head -n3 | awk '{print $2, $1}')

          echo "CONTRIBUTORS=${CONTRIBUTORS}" >> $GITHUB_ENV
          echo "MONTH_NAME=${MONTH_NAME}" >> $GITHUB_ENV

      - name: Log contributors
        run: |
          CONTRIBUTORS="${{ env.CONTRIBUTORS }}"
          MONTH_NAME="${{ env.MONTH_NAME }}"

          # Print the top 3 contributors of the month and the number of PRs they created
          echo "Top Contributors of $MONTH_NAME:"
          echo "$CONTRIBUTORS" | while read -r contributor count; do
            echo "- $contributor (PRs: $count)"
          done
