name: Internal Contributor of the Month

on:
  push:
    branches:
      - 'contributor-workflow'

jobs:
  determine-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine contributor
        id: determine
        run: |
          # Set the start and end dates for June 2023
          START_DATE="2023-06-01"
          END_DATE="2023-06-30"
          MONTH_NAME="June"

          # Exclude certain users
          EXCLUDED_USERS=("VadymSachenko" "lenadoc" "andriitserkovnyi" "AlexSlawinski")  # Add the usernames to be excluded here

          # Count PRs for each user
          declare -A PR_COUNTS=()

          PAGE=1
          while : ; do
            # Fetch merged pull requests within the specified date range
            PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github.v3+json" \
                   "https://api.github.com/repos/spryker/spryker-docs/pulls?state=closed&base=master&sort=created&direction=desc&merge_state=merged&page=$PAGE&per_page=100" \
                   | jq -r --arg START "$START_DATE" --arg END "$END_DATE" 'map(select(.merged_at >= $START and .merged_at <= $END)) | .[].user.login')

            if [ -z "$PRS" ]; then
              break
            fi

            for USER in $PRS; do
              if [[ ! " ${EXCLUDED_USERS[@]} " =~ " ${USER} " ]]; then
                PR_COUNTS[$USER]=$((PR_COUNTS[$USER]+1))
              fi
            done

            ((PAGE++))
          done

          # Prepare contributors list and sort by PR counts
          CONTRIBUTORS=()
          for USER in "${!PR_COUNTS[@]}"; do
            COUNT="${PR_COUNTS[$USER]}"
            CONTRIBUTORS+=("$COUNT:$USER")
          done
          IFS=$'\n' sorted=($(sort -nr <<<"${CONTRIBUTORS[*]}"))
          unset IFS

          # Prepare top 3 contributors list
          TOP_CONTRIBUTORS=""
          for i in 0 1 2; do
            if [[ $i -lt ${#sorted[@]} ]]; then
              PR_COUNT=${sorted[$i]%%:*}
              USERS=$(printf ', %s' $(grep -oP "(?<=^$PR_COUNT:).+" <<<"${sorted[@]}"))
              USERS=${USERS#, }
              TOP_CONTRIBUTORS+="$((i+1))nd place: $USERS (PRs: $PR_COUNT)\n"
            fi
          done

          echo "TOP_CONTRIBUTORS=${TOP_CONTRIBUTORS}" >> $GITHUB_ENV
          echo "MONTH_NAME=${MONTH_NAME}" >> $GITHUB_ENV

      - name: Log contributors
        run: |
          TOP_CONTRIBUTORS="${{ env.TOP_CONTRIBUTORS }}"
          MONTH_NAME="${{ env.MONTH_NAME }}"

          # Print top 3 contributors of the month and the number of PRs they created
          echo "Top 3 Contributors of $MONTH_NAME:"
          echo -e "$TOP_CONTRIBUTORS"
